Feature/elementwise
yhtang/FunFact pull request #29
Opened 2021-11-18 00:48 UTC by campsd

Implements issues #8 and #7

2021-11-18 06:52 UTC, yhtang requested changes

2021-11-18 06:52 UTC, yhtang commented on funfact/lang/interpreter/__init__.py
> +from ._elementwise import ElementEvaluator
Should it be called `ElementwiseEvaluator`? Does it feel too long? :laughing:

2021-11-18 06:52 UTC, yhtang commented on funfact/lang/interpreter/_slicing_propagation.py
> +                      *((slice(None),) * len(indices_none)))
Using a list here for `slice(None)` could be more concise.

2021-11-18 06:52 UTC, yhtang commented on funfact/lang/interpreter/_slicing_propagation.py
> +        indices_none = ordered_setminus(ordered_union(lhs.live_indices,
I understand `indices_none` refers to the indices that correspond to a range of `slice(None)`. However, the name by itself could be a little confusing at first glance. Could we rename it to something more intuitive?

2021-11-18 06:52 UTC, yhtang commented on funfact/model/_factorization.py
> +        return (self.tsrex | _index_slicer) | self._element_evaluator
I believe we can get rid of the parentheses here.

2021-11-18 06:52 UTC, yhtang commented on funfact/model/_factorization.py
> +    def getelements(self, idx):
It's better to name it `_get_elements` since we don't want users to call it directly.

2021-11-18 06:53 UTC, yhtang commented
Great job! I didn't realize the new evaluator itself needs only 3 lines. lol

2021-11-19 16:22 UTC, campsd commented
@yhtang  I have fixed the index ordering bug and added an extra test for Tucker decomposition.

2021-11-19 17:30 UTC, yhtang approved these changes

2021-11-19 17:30 UTC, merged