multi replica
yhtang/FunFact pull request #39
Opened 2021-11-22 22:15 UTC by campsd

Draft pull request working towards #14. 
The main outstanding issue is that the vectorizing index is not necessarily the last index after an Einstein operation.

2021-11-23 02:29 UTC, yhtang commented
Great!

> The main outstanding issue is that the vectorizing index is not necessarily the last index after an Einstein operation.

Can we solve it using the trick of directly setting `outidx` using the reordered live indices?

2021-11-23 02:54 UTC, yhtang requested changes

2021-11-23 02:54 UTC, yhtang commented on funfact/lang/interpreter/_vectorize.py
> +class Vectorizer():
This class can subclass TranscribeInterpreter, right? Then we don't need to redefine `__call__` again.

2021-11-23 21:41 UTC, campsd commented
Close #14.
I you want to vectorize a tensor expression, you have to run the index propagation before **and** after the vectorizer. The leaf initializer should only be run **after** vectorizing.

2021-11-24 17:12 UTC, campsd commented
The vectorizer now ensures:

- it doesn't modify the properties (shapes, ...) of the original tensor expression
- the vectorizing index is always last in a tensor expression

Example code snippet:
```
T = ff.tensor('T', 3, 3, 3)
u1 = ff.tensor('u_1', 10, 3)
u2 = ff.tensor('u_2', 20, 3)
u3 = ff.tensor('u_3', 30, 3)
i1, i2, i3, k1, k2, k3 = ff.indices('i_1, i_2, i_3, k_1, k_2, k_3')
tsrex = T[k1, k2, k3] * u1[i1, k1] * u2[i2, k2] * u3[i3, k3]
fac = Factorization(tsrex,nvec=4)
fac().shape
```

will return `(10, 20, 30, 4)` and `tsrex` will not be changed.

2021-11-24 18:28 UTC, yhtang approved these changes

2021-11-24 18:31 UTC, yhtang commented
Somehow, the history of this PR is a bit weird. For example, it even tries to update `CHANGELOG.md` which appears empty here but is actually populated upstream. I'm not sure what has gone wrong. :rofl:

2021-11-24 18:40 UTC, yhtang approved these changes

2021-11-24 18:41 UTC, merged